# Generated by Django 6.0.3 on 2026-04-02 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('chunk_type', models.CharField(max_length=50)),
                ('code_hash', models.CharField(max_length=64)),
                ('faiss_id', models.IntegerField()),
                ('explanation', models.TextField()),
                ('start_line', models.IntegerField(default=0)),
                ('end_line', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunk_indices', to='rag_core.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'symbol'], name='rag_core_ch_project_43a2a8_idx'), models.Index(fields=['project', 'file_path'], name='rag_core_ch_project_299a7b_idx')],
                'unique_together': {('project', 'symbol', 'file_path')},
            },
        ),
    ]
