# Generated by Django 6.0.3 on 2026-04-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_core', '0002_chunkindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True),
        ),
    ]
