# Generated by Django 6.0.3 on 2026-04-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_core', '0003_project_github_url'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chunkindex',
            name='rag_core_ch_project_299a7b_idx',
        ),
        migrations.AlterUniqueTogether(
            name='chunkindex',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='chunkindex',
            name='original_path',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='chunkindex',
            unique_together={('project', 'symbol', 'original_path')},
        ),
        migrations.AddIndex(
            model_name='chunkindex',
            index=models.Index(fields=['project', 'original_path'], name='rag_core_ch_project_9f6534_idx'),
        ),
    ]
