# Generated by Django 6.0.3 on 2026-04-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_core', '0004_remove_chunkindex_rag_core_ch_project_299a7b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='original_path',
            field=models.CharField(default='', max_length=500),
        ),
    ]
