# Generated by Django 6.0.3 on 2026-05-03 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag_core', '0006_chunkindex_input_tokens_chunkindex_output_tokens_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chunkindex',
            unique_together={('project', 'symbol', 'original_path', 'start_line', 'end_line')},
        ),
    ]
