# Generated by Django 6.0.3 on 2026-05-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_core', '0007_alter_chunkindex_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='indexing_step',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
